name: homelab

services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_db_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres17_db:/var/lib/postgresql/data
    secrets:
      - postgres_db_password

secrets:
  postgres_db_password:
    file: /run/secrets/postgres_db_password.txt

volumes:
  postgres17_db:
