
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

recorder:
  purge_keep_days: 365
  db_url: postgresql://homeassistant:DB_PW@DB_HOST/homeassistant

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
